const userString = prompt('Введите текст для обрезки').trim()
const startSliceIndex = prompt('Введите индекс, с которого нужно начать обрезку строки')
const endSliceIndex = prompt('Введите индекс, которым нужно закончить обрезку строки')
const resStr = userString.slice(startSliceIndex, endSliceIndex)
alert(`Результат: ${resStr}`)